package zelgius.com.barcodereader

/*
 * Copyright (C) The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import android.Manifest
import android.annotation.SuppressLint
import android.annotation.TargetApi
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.ImageFormat
import android.hardware.Camera
import android.hardware.Camera.CameraInfo
import android.media.CamcorderProfile
import android.media.MediaRecorder
import android.os.Build
import android.os.Environment
import android.os.SystemClock
import android.util.Log
import android.view.Surface
import android.view.SurfaceHolder
import android.view.WindowManager
import android.widget.Toast
import androidx.annotation.IntDef
import androidx.annotation.NonNull
import androidx.annotation.RequiresPermission
import androidx.annotation.StringDef
import com.google.android.gms.common.images.Size
import com.google.android.gms.vision.Detector
import com.google.android.gms.vision.Frame
import java.io.IOException
import java.lang.Thread.State
import java.lang.annotation.RetentionPolicy
import java.nio.ByteBuffer
import java.text.SimpleDateFormat
import java.util.*
import java.util.concurrent.locks.ReentrantLock
import kotlin.concurrent.withLock
import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.roundToInt

// Note: This requires Google Play Services 8.1 or higher, due to using indirect byte buffers for
// storing images.

/**
 * Manages the camera in conjunction with an underlying
 * [com.google.android.gms.vision.Detector].  This receives preview frames from the camera at
 * a specified rate, sending those frames to the detector as fast as it is able to process those
 * frames.
 *
 *
 * This camera source makes a best effort to manage processing on preview frames as fast as
 * possible, while at the same time minimizing lag.  As such, frames may be dropped if the detector
 * is unable to keep up with the rate of frames generated by the camera.  You should use
 * [CameraSource.Builder.setRequestedFps] to specify a frame rate that works well with
 * the capabilities of the camera hardware and the detector options that you have selected.  If CPU
 * utilization is higher than you'd like, then you may want to consider reducing FPS.  If the camera
 * preview or detector results are too "jerky", then you may want to consider increasing FPS.
 *
 *
 * The following Android permission is required to use the camera:
 *
 *  * android.permissions.CAMERA
 *
 */
@Suppress("DEPRECATION")
class CameraSource
//==============================================================================================
// Private
//==============================================================================================

/**
 * Only allow creation via the builder class.
 */
private constructor() {

    private var mContext: Context? = null

    private val mCameraLock = Any()

    // Guarded by mCameraLock
    private var mCamera: Camera? = null

    /**
     * Returns the selected camera; one of [.CAMERA_FACING_BACK] or
     * [.CAMERA_FACING_FRONT].
     */
     var cameraFacing = CAMERA_FACING_BACK
        private set

    /**
     * Rotation of the device, and thus the associated preview images captured from the device.
     * See [Frame.Metadata.getRotation].
     */
    private var mRotation: Int = 0

    /**
     * Returns the preview size that is currently in use by the underlying camera.
     */
    var previewSize: Size? = null
        private set
    /*
     * Returns the picture size that is currently in use
     */
    var pictureSize: Size? = null
        private set

    // These values may be requested by the caller.  Due to hardware limitations, we may need to
    // select close, but not exactly the same values for these.
    private var mRequestedFps = 30.0f

    private val formatter = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
    private var mediaRecorder: MediaRecorder? = null
    private var videoFile: String? = null
    private var videoStartCallback: VideoStartCallback? = null
    private var videoStopCallback: VideoStopCallback? = null
    private var videoErrorCallback: VideoErrorCallback? = null

    private var mFocusMode: String? = Camera.Parameters.FOCUS_MODE_AUTO
    private var mFlashMode: String? = Camera.Parameters.FLASH_MODE_AUTO

    private var previewSurfaceHolder: SurfaceHolder? = null

    /**
     * Dedicated thread and associated runnable for calling into the detector with frames, as the
     * frames become available from the camera.
     */
    private var mProcessingThread: Thread? = null
    private var mFrameProcessor: FrameProcessingRunnable? = null

    /**
     * Map to convert between a byte array, received from the camera, and its associated byte
     * buffer.  We use byte buffers internally because this is a more efficient way to call into
     * native code later (avoids a potential copy).
     */
    private val mBytesToByteBuffer = HashMap<ByteArray, ByteBuffer>()

    @StringDef(
        Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE,
        Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO,
        Camera.Parameters.FOCUS_MODE_AUTO,
        Camera.Parameters.FOCUS_MODE_EDOF,
        Camera.Parameters.FOCUS_MODE_FIXED,
        Camera.Parameters.FOCUS_MODE_INFINITY,
        Camera.Parameters.FOCUS_MODE_MACRO
    )
    @Retention(AnnotationRetention.SOURCE)
    private annotation class FocusMode

    @StringDef(
        Camera.Parameters.FLASH_MODE_ON,
        Camera.Parameters.FLASH_MODE_OFF,
        Camera.Parameters.FLASH_MODE_AUTO,
        Camera.Parameters.FLASH_MODE_RED_EYE,
        Camera.Parameters.FLASH_MODE_TORCH
    )
    @Retention(AnnotationRetention.SOURCE)
    private annotation class FlashMode

    @IntDef(
        CamcorderProfile.QUALITY_LOW,
        CamcorderProfile.QUALITY_HIGH,
        CamcorderProfile.QUALITY_480P,
        CamcorderProfile.QUALITY_720P,
        CamcorderProfile.QUALITY_1080P,
        CamcorderProfile.QUALITY_2160P,
        CamcorderProfile.QUALITY_CIF,
        CamcorderProfile.QUALITY_QCIF,
        CamcorderProfile.QUALITY_QVGA
    )
    @Retention(AnnotationRetention.SOURCE)
    private annotation class VideoMode

    //==============================================================================================
    // Builder
    //==============================================================================================

    /**
     * Builder for configuring and creating an associated camera source.
     */
    class Builder
    /**
     * Creates a camera source builder with the supplied context and detector.  Camera preview
     * images will be streamed to the associated detector upon starting the camera source.
     */
        (context: Context?, private val mDetector: Detector<*>?) {
        private var usesFaceDetector = false
        private val mCameraSource = CameraSource()

        init {
            if (context == null) {
                throw IllegalArgumentException("No context supplied.")
            }
            if (mDetector == null) {
                throw IllegalArgumentException("No detector supplied.")
            }

            usesFaceDetector = true
            mCameraSource.mContext = context
        }

        /**
         * Sets the requested frame rate in frames per second.  If the exact requested value is not
         * not available, the best matching available value is selected.   Default: 30.
         */
        fun setRequestedFps(fps: Float): Builder {
            if (fps <= 0) {
                throw IllegalArgumentException("Invalid fps: $fps")
            }
            mCameraSource.mRequestedFps = fps
            return this
        }

        fun setFocusMode(@FocusMode mode: String): Builder {
            mCameraSource.mFocusMode = mode
            return this
        }

        fun setFlashMode(@FlashMode mode: String): Builder {
            mCameraSource.mFlashMode = mode
            return this
        }

        /**
         * Sets the camera to use (either [.CAMERA_FACING_BACK] or
         * [.CAMERA_FACING_FRONT]). Default: back facing.
         */
        fun setFacing(facing: Int): Builder {
            if (facing != CAMERA_FACING_BACK && facing != CAMERA_FACING_FRONT) {
                throw IllegalArgumentException("Invalid camera: $facing")
            }
            mCameraSource.cameraFacing = facing
            return this
        }

        /**
         * Creates an instance of the camera source.
         */
        fun build(): CameraSource {
            if (usesFaceDetector)
                mCameraSource.mFrameProcessor = mCameraSource.FrameProcessingRunnable(mDetector)
            return mCameraSource
        }
    }

    //==============================================================================================
    // Bridge Functionality for the Camera1 API
    //==============================================================================================

    /**
     * Callback interface used to signal the moment of actual image capture.
     */
    interface ShutterCallback {
        /**
         * Called as near as possible to the moment when a photo is captured from the sensor. This
         * is a good opportunity to play a shutter sound or give other feedback of camera operation.
         * This may be some time after the photo was triggered, but some time before the actual data
         * is available.
         */
        fun onShutter()
    }

    /**
     * Callback interface used to supply image data from a photo capture.
     */
    interface PictureCallback {
        /**
         * Called when image data is available after a picture is taken.  The format of the data
         * is a jpeg binary.
         */
        fun onPictureTaken(pic: Bitmap)
    }

    /**
     * Callback interface used to indicate when video Recording Started.
     */
    interface VideoStartCallback {
        fun onVideoStart()
    }

    interface VideoStopCallback {
        //Called when Video Recording stopped.
        fun onVideoStop(videoFile: String?)
    }

    interface VideoErrorCallback {
        //Called when error ocurred while recording video.
        fun onVideoError(error: String?)
    }

    /**
     * Callback interface used to notify on completion of camera auto focus.
     */
    interface AutoFocusCallback {
        /**
         * Called when the camera auto focus completes.  If the camera
         * does not support auto-focus and autoFocus is called,
         * onAutoFocus will be called immediately with a fake value of
         * `success` set to `true`.
         *
         *
         * The auto-focus routine does not lock auto-exposure and auto-white
         * balance after it completes.
         *
         * @param success true if focus was successful, false if otherwise
         */
        fun onAutoFocus(success: Boolean)
    }

    /**
     * Callback interface used to notify on auto focus start and stop.
     *
     *
     *
     * This is only supported in continuous autofocus modes -- [ ][Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO] and [ ][Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE]. Applications can show
     * autofocus animation based on this.
     */
    interface AutoFocusMoveCallback {
        /**
         * Called when the camera auto focus starts or stops.
         *
         * @param start true if focus starts to move, false if focus stops to move
         */
        fun onAutoFocusMoving(start: Boolean)
    }

    //==============================================================================================
    // Public
    //==============================================================================================

    /**
     * Stops the camera and releases the resources of the camera and underlying detector.
     */
    fun release() {
        synchronized(mCameraLock) {
            stop()
            mFrameProcessor!!.release()
        }
    }

    /**
     * Opens the camera and starts sending preview frames to the underlying detector.  The supplied
     * surface holder is used for the preview so frames can be displayed to the user.
     *
     * @param surfaceHolder the surface holder to use for the preview frames
     * @throws IOException if the supplied surface holder could not be used as the preview display
     */
    @RequiresPermission(Manifest.permission.CAMERA)
    @Throws(IOException::class)
    fun start(surfaceHolder: SurfaceHolder): CameraSource? {
        synchronized(mCameraLock) {
            if (mCamera != null) {
                return this
            }
            try {
                previewSurfaceHolder = surfaceHolder
                val requestedCameraId = getIdForRequestedCamera(cameraFacing)
                if (requestedCameraId == -1) {
                    throw RuntimeException("Could not find requested camera.")
                }

                val camera = Camera.open(requestedCameraId)

                val pictureSize = getBestAspectPictureSize(camera, mContext)
                val previewSize = getBestAspectPreviewSize(camera, mContext)
                this.previewSize = Size(previewSize.width, previewSize.height)
                this.pictureSize = Size(pictureSize.width, pictureSize.height)
                val previewFpsRange = selectPreviewFpsRange(camera, mRequestedFps)
                    ?: throw RuntimeException("Could not find suitable preview frames per second range.")

                val parameters = camera.parameters
                parameters.setPictureSize(pictureSize.width, pictureSize.height)
                parameters.setPreviewSize(this.previewSize!!.width, this.previewSize!!.height)
                parameters.setPreviewFpsRange(
                    previewFpsRange[Camera.Parameters.PREVIEW_FPS_MIN_INDEX],
                    previewFpsRange[Camera.Parameters.PREVIEW_FPS_MAX_INDEX]
                )
                parameters.previewFormat = ImageFormat.NV21

                setRotation(camera, parameters, requestedCameraId)

                if (mFocusMode != null) {
                    if (parameters.supportedFocusModes.contains(mFocusMode)) {
                        parameters.focusMode = mFocusMode
                    } else {
                        Log.i(
                            TAG,
                            "Camera focus mode: $mFocusMode is not supported on this device."
                        )
                    }
                }

                // setting mFocusMode to the one set in the params
                mFocusMode = parameters.focusMode

                if (mFlashMode != null) {
                    if (parameters.supportedFlashModes != null) {
                        if (parameters.supportedFlashModes.contains(mFlashMode)) {
                            parameters.flashMode = mFlashMode
                        } else {
                            Log.i(
                                TAG,
                                "Camera flash mode: $mFlashMode is not supported on this device."
                            )
                        }
                    }
                }

                // setting mFlashMode to the one set in the params
                mFlashMode = parameters.flashMode

                camera.parameters = parameters

                // Four frame buffers are needed for working with the camera:
                //
                //   one for the frame that is currently being executed upon in doing detection
                //   one for the next pending frame to process immediately upon completing detection
                //   two for the frames that the camera uses to populate future preview images
                camera.setPreviewCallbackWithBuffer(CameraPreviewCallback())
                camera.addCallbackBuffer(createPreviewBuffer(this.previewSize!!))
                camera.addCallbackBuffer(createPreviewBuffer(this.previewSize!!))
                camera.addCallbackBuffer(createPreviewBuffer(this.previewSize!!))
                camera.addCallbackBuffer(createPreviewBuffer(this.previewSize!!))

                mCamera = camera

                mCamera!!.setPreviewDisplay(previewSurfaceHolder)
                mCamera!!.startPreview()

                mProcessingThread = Thread(mFrameProcessor)
                mFrameProcessor!!.setActive(true)
                mProcessingThread!!.start()

            } catch (e: RuntimeException) {
                e.printStackTrace()
                Toast.makeText(mContext, e.message, Toast.LENGTH_LONG).show()
                return null
            }

        }
        return this
    }

    /**
     * Closes the camera and stops sending frames to the underlying frame detector.
     *
     *
     * This camera source may be restarted again by calling [.start].
     *
     *
     * Call [.release] instead to completely shut down this camera source and release the
     * resources of the underlying detector.
     */
    fun stop() {
        synchronized(mCameraLock) {
            mFrameProcessor!!.setActive(false)
            if (mProcessingThread != null) {
                try {
                    // Wait for the thread to complete to ensure that we can't have multiple threads
                    // executing at the same time (i.e., which would happen if we called start too
                    // quickly after stop).
                    mProcessingThread!!.join()
                } catch (e: InterruptedException) {
                    Log.d(TAG, "Frame processing thread interrupted on release.")
                }

                mProcessingThread = null
            }

            // clear the buffer to prevent oom exceptions
            mBytesToByteBuffer.clear()

            if (mCamera != null) {
                mCamera!!.stopPreview()
                mCamera!!.setPreviewCallbackWithBuffer(null)
                try {
                    // We want to be compatible back to Gingerbread, but SurfaceTexture
                    // wasn't introduced until Honeycomb.  Since the interface cannot use a SurfaceTexture, if the
                    // developer wants to display a preview we must use a SurfaceHolder.  If the developer doesn't
                    // want to display a preview we use a SurfaceTexture if we are running at least Honeycomb.

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
                        mCamera!!.setPreviewTexture(null)

                    } else {
                        mCamera!!.setPreviewDisplay(null)
                    }
                } catch (e: Exception) {
                    Log.e(TAG, "Failed to clear camera preview: $e")
                }

                mCamera!!.release()
                mCamera = null
            }
        }
    }

    /*
     * Returns whether or not video can be recorded in specified quality
     */
    fun canRecordVideo(@VideoMode videoMode: Int): Boolean {
        return try {
            CamcorderProfile.get(getIdForRequestedCamera(cameraFacing), videoMode)
            true
        } catch (e: Exception) {
            false
        }

    }

    fun doZoom(scale: Float): Int {
        synchronized(mCameraLock) {
            if (mCamera == null) {
                return 0
            }
            var currentZoom = 0
            val maxZoom: Int
            val parameters = mCamera!!.parameters
            if (!parameters.isZoomSupported) {
                Log.w(TAG, "Zoom is not supported on this device")
                return currentZoom
            }
            maxZoom = parameters.maxZoom

            currentZoom = parameters.zoom + 1
            val newZoom: Float
            newZoom = if (scale > 1) {
                currentZoom + scale * (maxZoom / 10)
            } else {
                currentZoom * scale
            }
            currentZoom = newZoom.roundToInt() - 1
            if (currentZoom < 0) {
                currentZoom = 0
            } else if (currentZoom > maxZoom) {
                currentZoom = maxZoom
            }
            parameters.zoom = currentZoom
            mCamera!!.parameters = parameters
            return currentZoom
        }
    }

    /**
     * Initiates taking a picture, which happens asynchronously.  The camera source should have been
     * activated previously with [.start].  The camera preview is suspended
     * while the picture is being taken, but will resume once picture taking is done.
     *
     * @param shutter the callback for image capture moment, or null
     * @param jpeg    the callback for JPEG image data, or null
     */
    fun takePicture(shutter: ShutterCallback, jpeg: PictureCallback) {
        Log.d("ASD", "TRYING TO TAKE PICTURE")
        synchronized(mCameraLock) {
            if (mCamera != null) {
                setFlashMode(mFlashMode)
                val startCallback = PictureStartCallback()
                startCallback.mDelegate = shutter
                val doneCallback = PictureDoneCallback()
                doneCallback.mDelegate = jpeg
                mCamera!!.takePicture(startCallback, null, null, doneCallback)
            }
        }
    }

    /**
     * Initiates recording video.
     *
     * @param videoStartCallback the callback for video recording start
     * @param videoStopCallback the callback for video recording stop
     * @param videoErrorCallback the callback for video recording error
     */
    fun recordVideo(@NonNull videoStartCallback: VideoStartCallback, @NonNull videoStopCallback: VideoStopCallback, @NonNull videoErrorCallback: VideoErrorCallback) {
        this.videoStartCallback = videoStartCallback
        this.videoStopCallback = videoStopCallback
        this.videoErrorCallback = videoErrorCallback
        if (!checkCamera()) {
            this.videoErrorCallback!!.onVideoError("Camera Error")
            return
        }
        //PREPARE MEDIA RECORDER
        val cameraId = getIdForRequestedCamera(cameraFacing)
        //Step 0. Disable Shutter Sound
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            val camInfo = CameraInfo()
            Camera.getCameraInfo(cameraId, camInfo)
            if (camInfo.canDisableShutterSound) {
                mCamera!!.enableShutterSound(false)
            }
        }
        //Step 1. Unlock Camera
        mCamera!!.unlock()
        mediaRecorder = MediaRecorder()
        //Step 2. Create Camera Profile
        val profile: CamcorderProfile
        try {
            profile = CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P)
        } catch (e: Exception) {
            //CAMERA QUALITY TOO LOW!!!!!!!
            releaseMediaRecorder()
            this.videoErrorCallback!!.onVideoError("Camera quality too LOW")
            return
        }

        //Step 3. Set values in Profile except AUDIO settings
        mediaRecorder!!.setCamera(mCamera)
        mediaRecorder!!.setVideoSource(MediaRecorder.VideoSource.CAMERA)
        mediaRecorder!!.setOutputFormat(profile.fileFormat)
        mediaRecorder!!.setVideoEncoder(profile.videoCodec)
        mediaRecorder!!.setVideoEncodingBitRate(profile.videoBitRate)
        mediaRecorder!!.setVideoFrameRate(profile.videoFrameRate)
        mediaRecorder!!.setVideoSize(profile.videoFrameWidth, profile.videoFrameHeight)

        //Step 4. Set output file
        videoFile =
            Environment.getExternalStorageDirectory().toString() + "/" + formatter.format(Date()) + ".mp4"
        mediaRecorder!!.setOutputFile(videoFile)
        //Step 5. Set Duration
        mediaRecorder!!.setMaxDuration(-1)
        try {
            mediaRecorder!!.prepare()
        } catch (e: IllegalStateException) {
            releaseMediaRecorder()
            this.videoErrorCallback!!.onVideoError(e.message)
            return
        } catch (e: IOException) {
            releaseMediaRecorder()
            this.videoErrorCallback!!.onVideoError(e.message)
            return
        }

        mediaRecorder!!.start()
        //SEND RECORDING SIGNAL!
        this.videoStartCallback!!.onVideoStart()
    }

    fun stopVideo() {
        releaseMediaRecorder()
        this.videoStopCallback!!.onVideoStop(videoFile)
    }

    /**
     * Gets the current focus mode setting.
     *
     * @return current focus mode. This value is null if the camera is not yet created. Applications should call [ ][.autoFocus] to start the focus if focus
     * mode is FOCUS_MODE_AUTO or FOCUS_MODE_MACRO.
     * @see Camera.Parameters.FOCUS_MODE_AUTO
     *
     * @see Camera.Parameters.FOCUS_MODE_INFINITY
     *
     * @see Camera.Parameters.FOCUS_MODE_MACRO
     *
     * @see Camera.Parameters.FOCUS_MODE_FIXED
     *
     * @see Camera.Parameters.FOCUS_MODE_EDOF
     *
     * @see Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO
     *
     * @see Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE
     */
    @FocusMode
    fun getFocusMode(): String? {
        return mFocusMode
    }

    /**
     * Sets the focus mode.
     *
     * @param mode the focus mode
     * @return `true` if the focus mode is set, `false` otherwise
     * @see .getFocusMode
     */
    fun setFocusMode(@FocusMode mode: String?): Boolean {
        synchronized(mCameraLock) {
            if (mCamera != null && mode != null) {
                val parameters = mCamera!!.parameters
                if (parameters.supportedFocusModes.contains(mode)) {
                    parameters.focusMode = mode
                    mCamera!!.parameters = parameters
                    mFocusMode = mode
                    return true
                }
            }

            return false
        }
    }

    /**
     * Gets the current flash mode setting.
     *
     * @return current flash mode. null if flash mode setting is not
     * supported or the camera is not yet created.
     * @see Camera.Parameters.FLASH_MODE_OFF
     *
     * @see Camera.Parameters.FLASH_MODE_AUTO
     *
     * @see Camera.Parameters.FLASH_MODE_ON
     *
     * @see Camera.Parameters.FLASH_MODE_RED_EYE
     *
     * @see Camera.Parameters.FLASH_MODE_TORCH
     */
    @FlashMode
    fun getFlashMode(): String? {
        return mFlashMode
    }

    /**
     * Sets the flash mode.
     *
     * @param mode flash mode.
     * @return `true` if the flash mode is set, `false` otherwise
     * @see .getFlashMode
     */
    private fun setFlashMode(@FlashMode mode: String?): Boolean {
        synchronized(mCameraLock) {
            if (mCamera != null && mode != null) {
                val parameters = mCamera!!.parameters
                val supportedFlashModes = parameters.supportedFlashModes
                if (supportedFlashModes == null || supportedFlashModes.isEmpty() || supportedFlashModes.size == 1 && supportedFlashModes[0] == Camera.Parameters.FLASH_MODE_OFF) {
                    return false
                }
                if (supportedFlashModes.contains(mode)) {
                    parameters.flashMode = mode
                    mCamera!!.parameters = parameters
                    mFlashMode = mode
                    return true
                }
            }
            return false
        }
    }

    /**
     * Starts camera auto-focus and registers a callback function to run when
     * the camera is focused.  This method is only valid when preview is active
     * (between [.start] and before [.stop] or [.release]).
     *
     *
     *
     * Callers should check
     * [.getFocusMode] to determine if
     * this method should be called. If the camera does not support auto-focus,
     * it is a no-op and [AutoFocusCallback.onAutoFocus]
     * callback will be called immediately.
     *
     *
     *
     * If the current flash mode is not
     * [Camera.Parameters.FLASH_MODE_OFF], flash may be
     * fired during auto-focus, depending on the driver and camera hardware.
     *
     *
     *
     * @param cb the callback to run
     * @see .cancelAutoFocus
     */
    fun autoFocus(cb: AutoFocusCallback?) {
        synchronized(mCameraLock) {
            if (mCamera != null) {
                var autoFocusCallback: CameraAutoFocusCallback? = null
                if (cb != null) {
                    autoFocusCallback = CameraAutoFocusCallback()
                    autoFocusCallback.mDelegate = cb
                }
                mCamera!!.autoFocus(autoFocusCallback)
            }
        }
    }

    /**
     * Cancels any auto-focus function in progress.
     * Whether or not auto-focus is currently in progress,
     * this function will return the focus position to the default.
     * If the camera does not support auto-focus, this is a no-op.
     *
     * @see .autoFocus
     */
    fun cancelAutoFocus() {
        synchronized(mCameraLock) {
            if (mCamera != null) {
                mCamera!!.cancelAutoFocus()
            }
        }
    }

    /**
     * Sets camera auto-focus move callback.
     *
     * @param cb the callback to run
     * @return `true` if the operation is supported (i.e. from Jelly Bean), `false` otherwise
     */
    @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    fun setAutoFocusMoveCallback(cb: AutoFocusMoveCallback?): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
            return false
        }

        synchronized(mCameraLock) {
            if (mCamera != null) {
                var autoFocusMoveCallback: CameraAutoFocusMoveCallback? = null
                if (cb != null) {
                    autoFocusMoveCallback = CameraAutoFocusMoveCallback()
                    autoFocusMoveCallback.mDelegate = cb
                }
                mCamera!!.setAutoFocusMoveCallback(autoFocusMoveCallback)
            }
        }

        return true
    }

    /**
     * Wraps the camera1 shutter callback so that the deprecated API isn't exposed.
     */
    private inner class PictureStartCallback : Camera.ShutterCallback {
        var mDelegate: ShutterCallback? = null

        override fun onShutter() {
            mDelegate?.onShutter()
        }
    }

    /**
     * Wraps the final callback in the camera1 sequence, so that we can automatically turn the camera
     * preview back on after the picture has been taken.
     */
    private inner class PictureDoneCallback : Camera.PictureCallback {
        var mDelegate: PictureCallback? = null

        override fun onPictureTaken(data: ByteArray, camera: Camera) {
            if (mDelegate != null) {
                val pic = BitmapFactory.decodeByteArray(data, 0, data.size)
                mDelegate?.onPictureTaken(pic)
            }

            synchronized(mCameraLock) {
                if (mCamera != null) {
                    mCamera!!.startPreview()
                }
            }
        }
    }

    /**
     * Wraps the camera1 auto focus callback so that the deprecated API isn't exposed.
     */
    private inner class CameraAutoFocusCallback : Camera.AutoFocusCallback {
        var mDelegate: AutoFocusCallback? = null

        override fun onAutoFocus(success: Boolean, camera: Camera) {
            mDelegate?.onAutoFocus(success)
        }
    }

    /**
     * Wraps the camera1 auto focus move callback so that the deprecated API isn't exposed.
     */
    @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    private inner class CameraAutoFocusMoveCallback : Camera.AutoFocusMoveCallback {
        var mDelegate: AutoFocusMoveCallback? = null

        override fun onAutoFocusMoving(start: Boolean, camera: Camera) {
            mDelegate?.onAutoFocusMoving(start)
        }
    }

    /**
     * Selects the most suitable preview frames per second range, given the desired frames per
     * second.
     *
     * @param camera            the camera to select a frames per second range from
     * @param desiredPreviewFps the desired frames per second for the camera preview frames
     * @return the selected preview frames per second range
     */
    private fun selectPreviewFpsRange(camera: Camera, desiredPreviewFps: Float): IntArray? {
        // The camera API uses integers scaled by a factor of 1000 instead of floating-point frame
        // rates.
        val desiredPreviewFpsScaled = (desiredPreviewFps * 1000.0f).toInt()

        // The method for selecting the best range is to minimize the sum of the differences between
        // the desired value and the upper and lower bounds of the range.  This may select a range
        // that the desired value is outside of, but this is often preferred.  For example, if the
        // desired frame rate is 29.97, the range (30, 30) is probably more desirable than the
        // range (15, 30).
        var selectedFpsRange: IntArray? = null
        var minDiff = Integer.MAX_VALUE
        val previewFpsRangeList = camera.parameters.supportedPreviewFpsRange
        for (range in previewFpsRangeList) {
            val deltaMin = desiredPreviewFpsScaled - range[Camera.Parameters.PREVIEW_FPS_MIN_INDEX]
            val deltaMax = desiredPreviewFpsScaled - range[Camera.Parameters.PREVIEW_FPS_MAX_INDEX]
            val diff = abs(deltaMin) + abs(deltaMax)
            if (diff < minDiff) {
                selectedFpsRange = range
                minDiff = diff
            }
        }
        return selectedFpsRange
    }

    /**
     * Calculates the correct rotation for the given camera id and sets the rotation in the
     * parameters.  It also sets the camera's display orientation and rotation.
     *
     * @param parameters the camera parameters for which to set the rotation
     * @param cameraId   the camera id to set rotation based on
     */
    private fun setRotation(camera: Camera, parameters: Camera.Parameters, cameraId: Int) {
        val windowManager = mContext!!.getSystemService(Context.WINDOW_SERVICE) as WindowManager
        var degrees = 0
        when (windowManager.defaultDisplay.rotation) {
            Surface.ROTATION_0 -> degrees = 0
            Surface.ROTATION_90 -> degrees = 90
            Surface.ROTATION_180 -> degrees = 180
            Surface.ROTATION_270 -> degrees = 270
            else -> Log.e(TAG, "Bad rotation value")
        }

        val cameraInfo = CameraInfo()
        Camera.getCameraInfo(cameraId, cameraInfo)

        val angle: Int
        val displayAngle: Int
        if (cameraInfo.facing == CameraInfo.CAMERA_FACING_FRONT) {
            angle = (cameraInfo.orientation + degrees) % 360
            displayAngle = (360 - angle) % 360 // compensate for it being mirrored
        } else {  // back-facing
            angle = (cameraInfo.orientation - degrees + 360) % 360
            displayAngle = angle
        }

        // This corresponds to the rotation constants in {@link Frame}.
        mRotation = angle / 90

        camera.setDisplayOrientation(displayAngle)
        parameters.setRotation(angle)
    }

    /**
     * Creates one buffer for the camera preview callback.  The size of the buffer is based off of
     * the camera preview size and the format of the camera image.
     *
     * @return a new preview buffer of the appropriate size for the current camera settings
     */
    private fun createPreviewBuffer(previewSize: Size): ByteArray {
        val bitsPerPixel = ImageFormat.getBitsPerPixel(ImageFormat.NV21)
        val sizeInBits = (previewSize.height * previewSize.width * bitsPerPixel).toLong()
        val bufferSize = ceil(sizeInBits / 8.0).toInt() + 1
        //
        // NOTICE: This code only works when using play services v. 8.1 or higher.
        //
        // Creating the byte array this way and wrapping it, as opposed to using .allocate(),
        // should guarantee that there will be an array to work with.
        val byteArray = ByteArray(bufferSize)
        val buffer = ByteBuffer.wrap(byteArray)
        if (!buffer.hasArray() || !buffer.array().contentEquals(byteArray)) {
            // I don't think that this will ever happen.  But if it does, then we wouldn't be
            // passing the preview content to the underlying detector later.
            throw IllegalStateException("Failed to create valid buffer for camera source.")
        }
        mBytesToByteBuffer[byteArray] = buffer
        return byteArray
    }

    //==============================================================================================
    // Frame processing
    //==============================================================================================

    /**
     * Called when the camera has a new preview frame.
     */
    private inner class CameraPreviewCallback : Camera.PreviewCallback {
        override fun onPreviewFrame(data: ByteArray, camera: Camera) {
            mFrameProcessor!!.setNextFrame(data, camera)
        }
    }

    /**
     * This runnable controls access to the underlying receiver, calling it to process frames when
     * available from the camera.  This is designed to run detection on frames as fast as possible
     * (i.e., without unnecessary context switching or waiting on the next frame).
     *
     *
     * While detection is running on a frame, new frames may be received from the camera.  As these
     * frames come in, the most recent frame is held onto as pending.  As soon as detection and its
     * associated processing are done for the previous frame, detection on the mostly recently
     * received frame will immediately start on the same thread.
     */
    private inner class FrameProcessingRunnable internal constructor(private var mDetector: Detector<*>?) :
        Runnable {
        private val mStartTimeMillis = SystemClock.elapsedRealtime()

        // This lock guards all of the member variables below.
        private val lock = ReentrantLock()
        private val condition = lock.newCondition()
        private var mActive = true

        // These pending variables hold the state associated with the new frame awaiting processing.
        private var mPendingTimeMillis: Long = 0
        private var mPendingFrameId = 0
        private var mPendingFrameData: ByteBuffer? = null

        /**
         * Releases the underlying receiver.  This is only safe to do after the associated thread
         * has completed, which is managed in camera source's release method above.
         */
        @SuppressLint("Assert")
        internal fun release() {
            assert(mProcessingThread!!.state == State.TERMINATED)
            mDetector!!.release()
            mDetector = null
        }

        /**
         * Marks the runnable as active/not active.  Signals any blocked threads to continue.
         */
        internal fun setActive(active: Boolean) {
            lock.withLock {
                mActive = active
                condition.signalAll()
            }
        }

        /**
         * Sets the frame data received from the camera.  This adds the previous unused frame buffer
         * (if present) back to the camera, and keeps a pending reference to the frame data for
         * future use.
         */
        internal fun setNextFrame(data: ByteArray, camera: Camera) {
            lock.withLock {
                if (mPendingFrameData != null) {
                    camera.addCallbackBuffer(mPendingFrameData!!.array())
                    mPendingFrameData = null
                }
                if (!mBytesToByteBuffer.containsKey(data)) {
                    Log.d(
                        TAG,
                        "Skipping frame.  Could not find ByteBuffer associated with the image " + "data from the camera."
                    )
                    return
                }
                // Timestamp and frame ID are maintained here, which will give downstream code some
                // idea of the timing of frames received and when frames were dropped along the way.
                mPendingTimeMillis = SystemClock.elapsedRealtime() - mStartTimeMillis
                mPendingFrameId++
                mPendingFrameData = mBytesToByteBuffer[data]
                // Notify the processor thread if it is waiting on the next frame (see below).
                condition.signalAll()
            }
        }

        /**
         * As long as the processing thread is active, this executes detection on frames
         * continuously.  The next pending frame is either immediately available or hasn't been
         * received yet.  Once it is available, we transfer the frame info to local variables and
         * run detection on that frame.  It immediately loops back for the next frame without
         * pausing.
         *
         *
         * If detection takes longer than the time in between new frames from the camera, this will
         * mean that this loop will run without ever waiting on a frame, avoiding any context
         * switching or frame acquisition time latency.
         *
         *
         * If you find that this is using more CPU than you'd like, you should probably decrease the
         * FPS setting above to allow for some idle time in between frames.
         */
        override fun run() {
            var outputFrame: Frame? = null
            var data: ByteBuffer? = null

            while (true) {
                lock.withLock {
                    while (mActive && mPendingFrameData == null) {
                        try {
                            // Wait for the next frame to be received from the camera, since we
                            // don't have it yet.
                            condition.await()
                        } catch (e: InterruptedException) {
                            Log.d(TAG, "Frame processing loop terminated.", e)
                            return
                        }

                    }

                    if (!mActive) {
                        // Exit the loop once this camera source is stopped or released.  We check
                        // this here, immediately after the wait() above, to handle the case where
                        // setActive(false) had been called, triggering the termination of this
                        // loop.
                        return
                    }

                    //REDUCE SIZE OF CAMERA PREVIEW
                    val previewW = previewSize!!.width
                    val previewH = previewSize!!.height
                    //Log.d("ASD", "FRAME SIZE: "+previewW+"x"+previewH);
                    outputFrame = Frame.Builder()
                        .setImageData(
                            quarterNV21(mPendingFrameData!!, previewW, previewH),
                            previewW / 4,
                            previewH / 4,
                            ImageFormat.NV21
                        )
                        .setId(mPendingFrameId)
                        .setTimestampMillis(mPendingTimeMillis)
                        .setRotation(mRotation)
                        .build()

                    // Hold onto the frame data locally, so that we can use this for detection
                    // below.  We need to clear mPendingFrameData to ensure that this buffer isn't
                    // recycled back to the camera before we are done using that data.
                    data = mPendingFrameData!!
                    mPendingFrameData = null
                }

                // The code below needs to run outside of synchronization, because this will allow
                // the camera to add pending frame(s) while we are running detection on the current
                // frame.

                try {
                    mDetector!!.receiveFrame(outputFrame)
                } catch (t: Throwable) {
                    Log.e(TAG, "Exception thrown from receiver.", t)
                } finally {
                    mCamera!!.addCallbackBuffer(data?.array())
                }
            }
        }
    }

    private fun releaseMediaRecorder() {
        if (mediaRecorder != null) {
            mediaRecorder!!.stop()
            mediaRecorder!!.reset()
            mediaRecorder!!.release()
            mediaRecorder = null
            mCamera!!.lock()
        }
    }

    private fun checkCamera(): Boolean {
        return mCamera != null
    }

    companion object {
        @SuppressLint("InlinedApi")
        @JvmStatic
        val CAMERA_FACING_BACK = CameraInfo.CAMERA_FACING_BACK
        @SuppressLint("InlinedApi")
        @JvmStatic
        val CAMERA_FACING_FRONT = CameraInfo.CAMERA_FACING_FRONT

        private const val TAG = "CameraSource"
        private const val ratioTolerance = 0.1
        private const val maxRatioTolerance = 0.15

        /**
         * Gets the id for the camera specified by the direction it is facing.  Returns -1 if no such
         * camera was found.
         *
         * @param facing the desired camera (front-facing or rear-facing)
         */
        private fun getIdForRequestedCamera(facing: Int): Int {
            val cameraInfo = CameraInfo()
            for (i in 0 until Camera.getNumberOfCameras()) {
                Camera.getCameraInfo(i, cameraInfo)
                if (cameraInfo.facing == facing) {
                    return i
                }
            }
            return -1
        }

        fun getBestAspectPictureSize(camera: Camera, context: Context?): Camera.Size {
            val parameters = camera.parameters
            val supportedPictureSizes = parameters.supportedPictureSizes
            val targetRatio = Utils.getScreenRatio(context!!)
            var bestSize: Camera.Size? = null
            val diffs = TreeMap<Double, MutableList<Camera.Size>>()

            for (size in supportedPictureSizes) {
                val ratio = size.width.toFloat() / size.height
                val diff = abs(ratio - targetRatio).toDouble()
                if (diff < ratioTolerance) {
                    if (diffs.keys.contains(diff)) {
                        //add the value to the list
                        diffs[diff]!!.add(size)
                    } else {
                        val newList = ArrayList<Camera.Size>()
                        newList.add(size)
                        diffs[diff] = newList
                    }
                }
            }

            if (diffs.isEmpty()) {
                for (size in supportedPictureSizes) {
                    val ratio = size.width.toFloat() / size.height
                    val diff = abs(ratio - targetRatio).toDouble()
                    if (diff < maxRatioTolerance) {
                        if (diffs.keys.contains(diff)) {
                            //add the value to the list
                            diffs[diff]!!.add(size)
                        } else {
                            val newList = ArrayList<Camera.Size>()
                            newList.add(size)
                            diffs[diff] = newList
                        }
                    }
                }
            }

            //diffs now contains all of the usable sizes
            //now let's see which one has the least amount of
            for ((_, value) in diffs) {
                val entries = value as List<*>
                for (i in entries.indices) {
                    val s = entries[i] as Camera.Size
                    if (bestSize == null) {
                        bestSize = s
                    } else if (bestSize.width < s.width || bestSize.height < s.height) {
                        bestSize = s
                    }
                }
            }
            return bestSize ?: supportedPictureSizes[0]
        }

        fun getBestAspectPreviewSize(camera: Camera, context: Context?): Camera.Size {
            val parameters = camera.parameters
            val supportedPreviewSizes = parameters.supportedPreviewSizes
            val targetRatio = Utils.getScreenRatio(context!!)
            var bestSize: Camera.Size? = null
            val diffs = TreeMap<Double, MutableList<Camera.Size>>()

            for (size in supportedPreviewSizes) {
                val ratio = size.width.toFloat() / size.height
                val diff = abs(ratio - targetRatio).toDouble()
                if (diff < ratioTolerance) {
                    if (diffs.keys.contains(diff)) {
                        //add the value to the list
                        diffs[diff]!!.add(size)
                    } else {
                        val newList = ArrayList<Camera.Size>()
                        newList.add(size)
                        diffs[diff] = newList
                    }
                }
            }

            if (diffs.isEmpty()) {
                for (size in supportedPreviewSizes) {
                    val ratio = size.width.toFloat() / size.height
                    val diff = abs(ratio - targetRatio).toDouble()
                    if (diff < maxRatioTolerance) {
                        if (diffs.keys.contains(diff)) {
                            //add the value to the list
                            diffs[diff]!!.add(size)
                        } else {
                            val newList = ArrayList<Camera.Size>()
                            newList.add(size)
                            diffs[diff] = newList
                        }
                    }
                }
            }

            //diffs now contains all of the usable sizes
            //now let's see which one has the least amount of
            for ((_, value) in diffs) {
                val entries = value as List<*>
                for (i in entries.indices) {
                    val s = entries[i] as Camera.Size
                    if (s.height <= 1080 && s.width <= 1920) {
                        if (bestSize == null) {
                            bestSize = s
                        } else if (bestSize.width < s.width || bestSize.height < s.height) {
                            bestSize = s
                        }
                    }
                }
            }
            return bestSize ?: supportedPreviewSizes[0]
        }

        //RESIZE PREVIEW FRAMES TO HALF FOR A FASTER FACE DETECTION
        private fun quarterNV21(d: ByteBuffer, imageWidth: Int, imageHeight: Int): ByteBuffer {
            val data = d.array()
            val yuv = ByteArray(imageWidth / 4 * imageHeight / 4 * 3 / 2)
            // halve yuma
            var i = 0
            run {
                var y = 0
                while (y < imageHeight) {
                    var x = 0
                    while (x < imageWidth) {
                        yuv[i] = data[y * imageWidth + x]
                        i++
                        x += 4
                    }
                    y += 4
                }
            }
            // halve U and V color components
            var y = 0
            while (y < imageHeight / 2) {
                var x = 0
                while (x < imageWidth) {
                    yuv[i] = data[imageWidth * imageHeight + y * imageWidth + x]
                    i++
                    yuv[i] = data[imageWidth * imageHeight + y * imageWidth + (x + 1)]
                    i++
                    x += 8
                }
                y += 4
            }
            //REDUCED TO QUARTER QUALITY AND ONLY IN GRAY SCALE!
            return ByteBuffer.wrap(yuv)
        }
    }
}